#ifndef _ATFRAME_SERVICE_ATGATEWAY_PROTO_INNER_V1_CONFIG_H_
#define _ATFRAME_SERVICE_ATGATEWAY_PROTO_INNER_V1_CONFIG_H_

#pragma once


#if defined(LIBATFRAME_ATGATEWAY_ENABLE_OPENSSL)
#elif defined(LIBATFRAME_ATGATEWAY_ENABLE_MBEDTLS)
#elif defined(LIBATFRAME_ATGATEWAY_ENABLE_LIBRESSL)
#endif

#endif