# =========== server_frame =========== 
set (PROJECT_SERVER_FRAME_BAS_DIR ${CMAKE_CURRENT_LIST_DIR})
set (PROJECT_SERVER_FRAME_INC_DIR ${PROJECT_SERVER_FRAME_BAS_DIR})
set (PROJECT_SERVER_FRAME_SRC_DIR ${PROJECT_SERVER_FRAME_BAS_DIR})
set (PROJECT_SERVER_FRAME_LIB_LINK server_frame)
