
# =========== 3rdparty atframe_utils ==================
set (ATFRAMEWORK_ATFRAME_UTILS_BASE_DIR ${CMAKE_CURRENT_LIST_DIR})

if (ATFRAME_UTILS_ROOT)
    set (ATFRAMEWORK_ATFRAME_UTILS_PKG_DIR ${ATFRAME_UTILS_ROOT})
else()
    set (ATFRAMEWORK_ATFRAME_UTILS_PKG_DIR "${ATFRAMEWORK_ATFRAME_UTILS_BASE_DIR}/repo")
    if(NOT EXISTS ${ATFRAMEWORK_ATFRAME_UTILS_PKG_DIR})
        find_package(Git)
        execute_process(COMMAND ${GIT_EXECUTABLE} clone "https://github.com/atframework/atframe_utils.git" ${ATFRAMEWORK_ATFRAME_UTILS_PKG_DIR}
            WORKING_DIRECTORY ${ATFRAMEWORK_ATFRAME_UTILS_BASE_DIR}
        )
    endif()
endif()

set (ATFRAMEWORK_ATFRAME_UTILS_INC_DIR "${ATFRAMEWORK_ATFRAME_UTILS_PKG_DIR}/include")
set (ATFRAMEWORK_ATFRAME_UTILS_SRC_DIR "${ATFRAMEWORK_ATFRAME_UTILS_PKG_DIR}/src")
set (ATFRAMEWORK_ATFRAME_UTILS_LINK_NAME atframe_utils)


set (ATFRAME_UTILS_ROOT ${ATFRAMEWORK_ATFRAME_UTILS_PKG_DIR})
