file (GLOB_RECURSE PROTO_DESC_LIST_PBDESC
    "${CMAKE_CURRENT_LIST_DIR}/pbdesc/*.proto"
)

file (GLOB_RECURSE PROTO_DESC_LIST_CONFIG
    "${CMAKE_CURRENT_LIST_DIR}/config/*.proto"
)

# ============= configure protocols =============
set(PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR "${CMAKE_CURRENT_LIST_DIR}/config")
foreach(PROTO_FILE_FULL_PATH ${PROTO_DESC_LIST_CONFIG})
    file(RELATIVE_PATH PROTO_FILE ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR} ${PROTO_FILE_FULL_PATH})
    string(REGEX REPLACE "\\.proto$" "" PROTO_PATH_NAME ${PROTO_FILE_FULL_PATH})
    set(PROTO_SRC "${PROTO_PATH_NAME}.pb.h" "${PROTO_PATH_NAME}.pb.cc")

    list(APPEND PROJECT_SERVER_FRAME_PROTO_FILES ${PROTO_FILE})
    list(APPEND PROJECT_SERVER_FRAME_PROTO_SRCS ${PROTO_SRC})
    list(APPEND SRC_LIST ${PROTO_SRC})
endforeach()
add_custom_command(OUTPUT ${PROJECT_SERVER_FRAME_PROTO_SRCS}
    COMMAND ${PROTOBUF_PROTOC_EXECUTABLE}
    --proto_path ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}
    --cpp_out ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}
    #-o "${PROJECT_INSTALL_RES_PBD_DIR}/config.pb"
    ${PROTO_DESC_LIST_CONFIG}
    WORKING_DIRECTORY ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}
    DEPENDS ${PROTO_DESC_LIST_CONFIG}
    COMMENT "Generate [@${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}] ${PROJECT_SERVER_FRAME_PROTO_FILES}"
)

# ============= network protocols =============
unset(PROJECT_SERVER_FRAME_PROTO_FILES)
unset(PROJECT_SERVER_FRAME_PROTO_SRCS)
unset(PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR)
set(PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR "${CMAKE_CURRENT_LIST_DIR}/pbdesc")

foreach(PROTO_FILE_FULL_PATH ${PROTO_DESC_LIST_PBDESC})
    file(RELATIVE_PATH PROTO_FILE ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR} ${PROTO_FILE_FULL_PATH})
    string(REGEX REPLACE "\\.proto$" "" PROTO_PATH_NAME ${PROTO_FILE_FULL_PATH})
    set(PROTO_SRC "${PROTO_PATH_NAME}.pb.h" "${PROTO_PATH_NAME}.pb.cc")

    list(APPEND PROJECT_SERVER_FRAME_PROTO_FILES ${PROTO_FILE})
    list(APPEND PROJECT_SERVER_FRAME_PROTO_SRCS ${PROTO_SRC})
    list(APPEND SRC_LIST ${PROTO_SRC})
endforeach()

add_custom_command(OUTPUT ${PROJECT_SERVER_FRAME_PROTO_SRCS}
    COMMAND ${PROTOBUF_PROTOC_EXECUTABLE}
    --proto_path ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}
    --cpp_out ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}
    #-o "${PROJECT_INSTALL_RES_PBD_DIR}/config.pb"
    ${PROTO_DESC_LIST_PBDESC}
    WORKING_DIRECTORY ${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}
    DEPENDS ${PROTO_DESC_LIST_PBDESC}
    COMMENT "Generate [@${PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR}] ${PROJECT_SERVER_FRAME_PROTO_FILES}"
)

unset(PROJECT_SERVER_FRAME_PROTO_FILES)
unset(PROJECT_SERVER_FRAME_PROTO_SRCS)
unset(PROJECT_SERVER_FRAME_PROTO_RELATIVE_DIR)